function generate_microstructure(nPriorBeta, oriBetaInput, nColoniesMax, lamwidthBeta, lamRatio, microstructureId, runName, orientationId, outputDir)
    rng('default');
    rng(microstructureId);

    textureStrength = 0;
    nColoniesMin = nColoniesMax;

    write_neper_script( ...
        nPriorBeta, ...
        oriBetaInput, ...
        nColoniesMin, ...
        nColoniesMax, ...
        lamwidthBeta, ...
        outputDir, ...
        microstructureId, ...
        lamRatio, ...
        textureStrength ...
    );
end
